# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

source 'https://rubygems.org'

gem 'rspec'
gem 'sinatra'
gem 'capybara'
# gem "rails"
